---
title: "Final Project Code"
author: "Desiree"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(plyr)
library(naniar)
library(vegan)
library(ggpubr)
library(labdsv)

# Importing data
benthic <- read.csv("FakeBenthicDataset.csv",header=TRUE)
# viewing the data
benthic

summary(benthic)

```
```{r}
# change - to NA
benthic$Carapace.Length..mm._NA <- gsub("-", 0, benthic$Carapace.Length..mm.) %>% as.numeric() %>% tidyr::replace_na(0)
benthic$Shell.Length_NA <- gsub("-", 0, benthic$Shell.Length) %>% as.numeric() %>% tidyr::replace_na(0)
benthic$Worm.Length_NA <- gsub("-", 0, benthic$Worm.Length) %>% as.numeric() %>% tidyr::replace_na(0)

benthic %>% naniar::replace_with_na(replace = list(x = 0))
```

```{r filtering}

#The simplest measure of species richness is just the number of species recorded per site. That is, the number of species that have more than one individual recorded.
#ddply(benthic,~Location,function(x) {data.frame(RICHNESS=sum(x[-1]>0))})

#mean carapace length per species per location
benthic %>% group_by(Location,Species) %>% dplyr::summarise(mean = mean(as.numeric(Carapace.Length..mm._NA))) -> test
```

```{r richness}
#counting species richness per location
richness <- dplyr::count(test, Location)
richness

ggplot(richness, aes(x=Location, y=n)) +
  geom_point() + 
  geom_segment( aes(x=Location, xend=Location, y=0, yend=n)) +
  theme(legend.position = "none") +
  labs(x = "Data Collection Site",
       y = "Species Richness",
       title = "Species Richness Per Site")
```
```{r count}

numspecies <- benthic %>% dplyr::count (Location, Species)

```

```{r long_data}

data_wide <- spread(numspecies, Species, n)
data_wide

data_wide[is.na(data_wide)] <- 0

```

```{r row_names}

rownames(data_wide) <- data_wide$Location
data_wide$Location <- NULL

```

```{r diversity}

#shannon diversity test on species present
shannon <- diversity(data_wide,index = "shannon") %>% as.data.frame()
shannon$Location <- rownames(shannon)
```

```{r plot_shannon}

plot_shandiv <- ggplot(shannon, aes(x = Location, y = ., fill = Location)) +
  geom_col(color = "black") +
  theme(legend.position = "none") +
  labs(x = "Data Collection Site",
       y = "Mean Shannon Diversity",
       title = "Shannon Diversity Per Site")
plot_shandiv

```

...

